### ISSUE TITLE
Task fails with 'Cannot read property Length of undefined'

### ISSUE THREAD

**Issue by fwielstra** [daniellmb/grunt-istanbul-coverage#10]
This is probably due to some version mismatches, but I haven't been able to figure it out. I've been updating some libs and ran into this issue.

I generate a JSON coverage file via karma-coverage 0.2.4 (latest), which internally uses istanbul ~0.2.10 to generate reports. That file is then read by grunt-istanbul-coverage 0.0.5, which uses istanbul ~0.2.6 to read reports.

The task fails with the following error + stack trace:

```
Fatal error: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at ~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/object-utils.js:244:37
    at Array.forEach (native)
    at Object.mergeFileCoverage (~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/object-utils.js:241:31)
    at ~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/collector.js:70:44
    at Array.forEach (native)
    at Object.Collector.add (~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/collector.js:67:31)
    at ~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/command/check-coverage.js:78:27
    at Array.forEach (native)
    at ~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/command/check-coverage.js:76:19
    at ~/project/node_modules/grunt-istanbul-coverage/node_modules/istanbul/lib/util/file-matcher.js:35:9
```

I fiddled a bit by upping the istanbul version inside grunt-istanbul-coverage in my project to 0.2.10, but to no avail.

**Comment by ToffeeLu** [comment]
@johnfriz great thanks for your digging!
